<?xml version="1.0" encoding="UTF-8"?>
<wsdl:description xmlns:wsdl="http://www.w3.org/ns/wsdl" 
				  xmlns:http="http://www.w3.org/ns/wsdl/http" 
				  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
				  xmlns:tns="http://jw.nju.edu.cn/wsdl" 
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:ss="http://jw.nju.edu.cn/schema"
				  targetNamespace="http://jw.nju.edu.cn/wsdl">
				  
				  
  <!-- 
  author:zhr
  description要声明import的xsd的命名空间
  types中定义各种参数
   -->
				  
  <wsdl:types>
  	<xsd:schema xmlns:myschema="http://jw.nju.edu.cn/schema"
  				xmlns="http://www.w3.org/2001/XMLSchema"
  				targetNamespace="http://jw.nju.edu.cn/wsdl">
  		<xsd:import 
  			namespace="http://jw.nju.edu.cn/schema"
  			schemaLocation="../xsd/ScoreList.xsd"></xsd:import>
  			
  		<!-- 定义错误信息 -->
  		<xsd:element name="invalidDataError" type="string"></xsd:element>
  		
  		<!-- add指添加成绩，request是scoreList，response是string字符串 -->
  		<xsd:element name="add" type="myschema:课程成绩列表类型"></xsd:element>
  		<xsd:element name="addResponse" type="string"></xsd:element>

  	</xsd:schema>
  </wsdl:types>
  	
  <!-- 添加 -->
  <wsdl:interface name="addScoreInterface">
  	<!-- 出错信息，已在types中定义 -->
  	<wsdl:fault name="invalidDataFault" 
  				element="tns:invalidDataError"></wsdl:fault>
  				
  	<!-- 添加得分 -->
    <wsdl:operation name="addScore"
    				pattern="http://www.w3.org/ns/wsdl/in-out">
      <wsdl:input messageLabel="In" element="tns:add"/>
      <wsdl:output messageLabel="Out" element="tns:addResponse"/>
    </wsdl:operation>
  </wsdl:interface>
  
  
  <!-- http绑定 -->
  <wsdl:binding name="addScoreHTTPBinding" 
  				interface="tns:addScoreInterface"
  				type="http://www.w3.org/ns/wsdl/http"
  				http:methodDefault="POST">
    <wsdl:operation ref="tns:addScore"
    				http:location="{tns:add}"/>
  </wsdl:binding>
  
  <!-- 
  name设成具体的webservice类名，interface是上面定义的interface
  binding用上面定义的binding
  address是服务器的地址
   -->
  <wsdl:service name="addScoreService"
  				interface="tns:addScoreInterface">
  	<wsdl:endpoint name="addScoreEndpoint"
  				   binding="addScoreHTTPBinding"
  				   address="http://localhost:8080/addScore"/>    
  </wsdl:service>
  
</wsdl:description>